### PR TITLE
Added PhpMetrics to phaudit docker

### PR DESCRIPTION
**Pull request by pborreli**
FYI : I didn't test it :see_no_evil:

### CODE REVIEW

**Comment by joelwurtz** [comment]
I was already doing it xD, hum as you commit is before mine i will rollback and merge yours

**Comment by joelwurtz** [comment]
Thanks ! as you don't :beer: here is a :bear:

**Comment by pborreli** [comment]
thanks but I don't drink :bear:

**Comment by pborreli** [comment]
let's have a :coffee: instead ?

**Pull request merged**
